// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycseesguvxmvdvxkeoiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inljc2Vlc2d1dnhtdmR2eGtlb2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Njk3NTEsImV4cCI6MjA1ODI0NTc1MX0.JRi3q5Ej228lC3E7LdErJi97CHLr_y20F2yNaxeJeT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);